language: ruby
sudo: false
git:
  depth: false
cache: bundler
before_install:
 - rm -f Gemfile.lock Gemfile Rakefile
 - wget https://raw.githubusercontent.com/progit/progit2-pub/master/Gemfile
 - wget https://raw.githubusercontent.com/progit/progit2-pub/master/Rakefile
 - bundle install
script: bundle exec rake book:build
after_success: bundle exec rake book:tag
deploy:
  provider: releases
  file:
  - progit.epub
  - progit.mobi
  - progit.pdf
  skip_cleanup: true
  on:
    tags: true
  api-key: $GITHUB_API_TOKEN
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/

addons:
  apt:
    packages:
      - epubcheck
notifications:
  email:
    on_success: never
    on_failure: always
